CI: update publish
Signed-off-by: Luke-zhang-04 <luke.zhang2004dev@gmail.com>

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -22,6 +22,7 @@ jobs:
     - run: yarn add sass -D
 
     - name: publish to NPM
-      run: yarn publish --access public
+      # Don't fail if version already exists
+      run: yarn publish --access public || echo "Version already published" && exit 0
       env:
         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
